## Docker Compose file for the Base Auth API in stage
version: '3.9'

services:
  api:
    env_file:
      - environments/stage.env
    environment:
      - ENVIRONMENT=stage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  nestjs-2024-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DATABASE:-nestjs-2024}'
    volumes:
      - ./nestjs-2024-api-db:/var/lib/postgresql/nestjs-2024
    restart: unless-stopped

  nestjs-2024-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

volumes:
  nestjs-2024-api-db: